"""PDF generation service using WeasyPrint + Jinja2.

Renders a payslip HTML template and converts it to a PDF byte string.
The generated bytes can be streamed directly as a FastAPI StreamingResponse.
"""

import calendar
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

_jinja_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATES_DIR)),
    autoescape=select_autoescape(["html"]),
)

# ── Jinja2 custom filters ──────────────────────────────────────────────────


def _fmt_inr(value: float | int | None) -> str:
    """Format a number as Indian Rupee with comma grouping (e.g. 1,18,500.00)."""
    if value is None:
        return "0.00"
    value = float(value)
    negative = value < 0
    value = abs(value)
    integer_part = int(value)
    decimal_part = round((value - integer_part) * 100)

    # Indian number grouping: last 3 digits, then groups of 2
    s = str(integer_part)
    if len(s) <= 3:
        grouped = s
    else:
        grouped = s[-3:]
        s = s[:-3]
        while s:
            grouped = s[-2:] + "," + grouped
            s = s[:-2]

    result = f"{grouped}.{decimal_part:02d}"
    return f"−{result}" if negative else result


def _num2words_inr(amount: float) -> str:
    """Convert a rupee amount to words (e.g. 'Rupees Twelve Thousand Five Hundred Only')."""
    ones = [
        "", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
        "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
        "Seventeen", "Eighteen", "Nineteen",
    ]
    tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]

    def _say(n: int) -> str:
        if n == 0:
            return ""
        elif n < 20:
            return ones[n]
        elif n < 100:
            return tens[n // 10] + (" " + ones[n % 10] if n % 10 else "")
        else:
            return ones[n // 100] + " Hundred" + (" " + _say(n % 100) if n % 100 else "")

    rupees = int(amount)
    paise = round((amount - rupees) * 100)

    if rupees == 0:
        words = "Zero"
    elif rupees < 1000:
        words = _say(rupees)
    elif rupees < 100_000:
        words = _say(rupees // 1000) + " Thousand" + (" " + _say(rupees % 1000) if rupees % 1000 else "")
    elif rupees < 10_000_000:
        lakh = rupees // 100_000
        rem = rupees % 100_000
        words = _say(lakh) + " Lakh" + (" " + _say(rem) if rem else "")
    else:
        crore = rupees // 10_000_000
        rem = rupees % 10_000_000
        words = _say(crore) + " Crore" + (" " + _say(rem) if rem else "")

    result = f"Rupees {words}"
    if paise:
        result += f" and {_say(paise)} Paise"
    return result + " Only"


_jinja_env.filters["fmt_inr"] = _fmt_inr

# ── Public API ─────────────────────────────────────────────────────────────


def render_payslip_pdf(
    *,
    company: Any,
    employee: Any,
    item: Any,
    run_id: str,
    month: int,
    year: int,
) -> bytes:
    """Render a payslip for one employee and return PDF bytes.

    Args:
        company: Company ORM model instance.
        employee: Employee ORM model instance.
        item: PayrollLineItem ORM model instance (with .snapshot JSONB).
        run_id: UUID string of the PayrollRun (used for display only).
        month: Payroll month (1–12).
        year: Payroll year.

    Returns:
        Raw PDF bytes suitable for streaming in a FastAPI response.
    """
    snapshot: dict = item.snapshot or {}

    working_days_std = int(snapshot.get("working_days_per_month", 26))
    working_days_present = int(snapshot.get("working_days", 0))
    leave_deduction_days = int(snapshot.get("unpaid_leave_days", 0))
    overtime_hours = snapshot.get("overtime_hours", 0.0)

    template_ctx = {
        "company": company,
        "employee": employee,
        "item": item,
        "snapshot": snapshot,
        "run_id_short": str(run_id)[:8].upper(),
        "month": month,
        "year": year,
        "month_name": calendar.month_name[month],
        "working_days_std": working_days_std,
        "working_days_present": working_days_present,
        "leave_deduction_days": leave_deduction_days,
        "overtime_hours": overtime_hours,
        "net_pay_words": _num2words_inr(item.net_pay),
        "generated_at": datetime.now(tz=timezone.utc).strftime("%d %b %Y, %H:%M UTC"),
    }

    template = _jinja_env.get_template("payslip.html")
    html_str = template.render(**template_ctx)

    # Lazy import so a missing OS lib doesn't crash the whole server at startup
    from weasyprint import HTML  # noqa: PLC0415
    pdf_bytes: bytes = HTML(string=html_str, base_url=str(_TEMPLATES_DIR)).write_pdf()
    return pdf_bytes
